add: gopx-webui
manuarora700/indiehackersarmy pull request #4
Opened 2024-08-09 07:32 UTC by GopalVerma1303

2024-08-09 07:40 UTC, manuarora700 commented
@GopalVerma1303 can you please rebase with main?

2024-08-09 07:43 UTC, GopalVerma1303 commented
> @GopalVerma1303 can you please rebase with main?

Sure!

2024-08-10 15:46 UTC, ABSphreak requested changes

2024-08-10 15:46 UTC, ABSphreak commented on next.config.mjs
>      ],
@GopalVerma1303 Add `tryhoverify.com` here too

2024-08-10 16:48 UTC, GopalVerma1303 commented on next.config.mjs
>      ],
Added

2024-08-10 16:52 UTC, GopalVerma1303 commented
No conflicts detected with the base branch. Please review and merge. Thank you.

2024-08-11 10:57 UTC, merged